/*
 *                LEGL 2025-2026 HydraSystems.
 *
 *  This program is free software; you can redistribute it and/or   
 *  modify it under the terms of the GNU General Public License as  
 *  published by the Free Software Foundation; either version 2 of  
 *  the License, or (at your option) any later version.             
 *                                                                  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of  
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the   
 *  GNU General Public License for more details.                    
 * 
 *  Based on a design by LVGL Kft
 * 
 * =====================================================================
 *
 * Edit     Date     Version       Edit Description
 * ====  ==========  ======= ===========================================
 * SJ    2025/08/18   1.a.1    Original by LVGL Kft
 *
 */

#pragma once

#include <stdint.h>
#include <stddef.h>

#include "EG_IntrnlConfig.h"
#include "core/EG_Object.h"
#include "draw/EG_ImageBuffer.h"

#if EG_USE_SNAPSHOT

/** Take snapshot for object with its children.
 *
 * @param obj    The object to generate snapshot.
 * @param cf     color format for generated image.
 *
 * @return a pointer to an image descriptor, or NULL if failed.
 */
EGImageBuffer* EG_TakeSnapshot(EGObject *pObj, EG_ImageColorFormat_t ColorFormat);

/** Free the snapshot image returned by @ref lv_snapshot_take
 *
 * It will firstly free the data image takes, then the image descriptor.
 *
 * @param dsc    The image descriptor generated by lv_snapshot_take.
 *
 */
void EG_FreeSnapshot(EGImageBuffer *pImageBuffer);

/** Get the buffer needed for object snapshot image.
 *
 * @param obj    The object to generate snapshot.
 * @param cf     color format for generated image.
 *
 * @return the buffer size needed in bytes
 */
uint32_t EG_SnapshotBufferSizeRequired(EGObject *pObj, EG_ImageColorFormat_t ColorFormat);

/** Take snapshot for object with its children, save image info to provided buffer.
 *
 * @param obj      The object to generate snapshot.
 * @param cf       color format for generated image.
 * @param dsc      image descriptor to store the image result.
 * @param buf      the buffer to store image data.
 * @param buf_size provided buffer size in bytes.
 *
 * @return EG_RES_OK on success, EG_RES_INVALID on error.
 */
EG_Result_t EG_TakeSnapshotToBuffer(EGObject *pObj, EG_ImageColorFormat_t ColorFormat, EGImageBuffer *pImageBuffer, void *pBuffer, uint32_t BufferSize);

#endif